services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    # No password for development
    command: redis-server --appendonly yes

  app:
    image: eks-products-app
    container_name: eks-products
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # No password needed
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
