replicaCount: 5

image:
  repository: ${ECR_REPOSITORY_URL}
  tag: "latest"

service:
  type: LoadBalancer

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 20

persistence:
  enabled: true
  storageClass: "gp3"
  size: 10Gi

redis:
  enabled: true
  master:
    persistence:
      size: 5Gi
